#!/bin/bash
SRC=src
OUT=static

dev(){
	echo watching $SRC ...
	while inotifywait -q -e MODIFY -r $SRCDIR; do
		build
	done
}

build(){
	mkdir -p $OUT
	while IFS= read p;do
		if [[ "$p" =~ ^import.\"([^\"]*)\"$ ]];then
			echo "let ${BASH_REMATCH[1]} = Vue.component('${BASH_REMATCH[1]}', $(cat src/${BASH_REMATCH[1]}.js));"
		else
			echo "$p";
		fi
	done < $SRC/index.html > $OUT/index.html;
}

$@